import os
import shutil
from pipeline.video_worker import process_video

# Reads sources from, and writes _fast/_studio pairs into, this directory —
# which is also what the app's Compare page scans. Not "input/1:1": a colon is
# illegal in a Windows path (it's the alternate-data-stream separator), so
# os.makedirs there raises NotADirectoryError [WinError 267].
INPUT_DIR = os.environ.get("SX_PAIRS_DIR", os.path.join("output", "pairs"))

def main():
    if not os.path.exists(INPUT_DIR):
        print(f"Directory {INPUT_DIR} does not exist.")
        print(f"Create it and drop source videos in, or set SX_PAIRS_DIR.")
        return

    # Skip files that were already generated by this script
    files = [f for f in os.listdir(INPUT_DIR) if f.lower().endswith((".mp4", ".mov", ".avi", ".webm")) 
             and not f.endswith("_fast.mp4") and not f.endswith("_studio.mp4")]
             
    if not files:
        print("No original videos found in input directory to process.")
        return

    print(f"Found {len(files)} original videos. Starting batch upscale...")

    def console_log(msg):
        print(f"  [STATUS] {msg}")

    for file in files:
        file_path = os.path.join(INPUT_DIR, file)
        base_name, ext = os.path.splitext(file)
        
        # Paths for output
        fast_out = os.path.join(INPUT_DIR, f"{base_name}_fast.mp4")
        studio_out = os.path.join(INPUT_DIR, f"{base_name}_studio.mp4")

        print(f"\nProcessing: {file}")
        
        # 1. Fast upscale
        if not os.path.exists(fast_out):
            print("  -> Running Fast (Lanczos4+CAS) Upscale...")
            try:
                _, upscaled_local = process_video(
                    video_path=file_path,
                    prompt=None,
                    upscale_only=True,
                    sharpening=0.5,
                    upscale_engine="fast",
                    status_callback=console_log
                )
                shutil.copy(upscaled_local, fast_out)
                print(f"  -> Saved {fast_out}")
            except Exception as e:
                print(f"  -> Error in Fast upscale: {e}")
        else:
            print(f"  -> {fast_out} already exists. Skipping.")

        # 2. Studio upscale
        if not os.path.exists(studio_out):
            print("  -> Running Studio (znedi3+FineSharp) Upscale...")
            try:
                _, upscaled_local = process_video(
                    video_path=file_path,
                    prompt=None,
                    upscale_only=True,
                    sharpening=0.0,
                    upscale_engine="studio",
                    status_callback=console_log
                )
                shutil.copy(upscaled_local, studio_out)
                print(f"  -> Saved {studio_out}")
            except Exception as e:
                print(f"  -> Error in Studio upscale: {e}")
        else:
            print(f"  -> {studio_out} already exists. Skipping.")

if __name__ == "__main__":
    main()
